    use simpsonsIntegrationParallel;
    use simpsonsIntegration;
    use testFunctions;
    use Time;

    var exact:real;
    var calculated:real;
    var maxErr:real;
    var timer, timerP:Timer;
    var timerMargin: real = 0.6;

    exact = 0.25;
    maxErr = 0.00001;
    timerP.start();
    calculated = simpsonsIntegrationParallel(a = 0.0, b = 1.0, N = 100, f = f1);
    timerP.stop();
    writeln((abs(calculated - exact) <= maxErr));
    timer.start();
    calculated = simpsonsIntegration(a = 0.0, b = 1.0, N = 100, f = f1);
    timer.stop();
    writeln((abs(calculated - exact) <= maxErr));
    writeln((timerP.elapsed() < timerMargin*timer.elapsed()));

    exact = 4.605170;
    maxErr = 0.00001;
    timerP.clear();
    timerP.start();
    calculated = simpsonsIntegrationParallel(a = 1.0, b = 100.0, N = 1000, f = f2);
    timerP.stop();
    writeln((abs(calculated - exact) <= maxErr));
    timer.clear();
    timer.start();
    calculated = simpsonsIntegration(a = 1.0, b = 100.0, N = 1000, f = f2);
    timer.stop();
    writeln((abs(calculated - exact) <= maxErr));
    writeln((timerP.elapsed() < 0.5*timer.elapsed()));

    exact = 12500000;
    maxErr = 0.00001;
    timerP.clear();
    timerP.start();
    calculated = simpsonsIntegrationParallel(a = 0.0, b = 5000.0, N = 5000000, f = f3);
    timerP.stop();
    writeln((abs(calculated - exact) <= maxErr));
    timer.clear();
    timer.start();
    calculated = simpsonsIntegration(a = 0.0, b = 5000.0, N = 5000000, f = f3);
    timer.stop();
    writeln((abs(calculated - exact) <= maxErr));
    writeln((timerP.elapsed() < timerMargin*timer.elapsed()));

    exact = 18000000;
    maxErr = 0.00001;
    timerP.clear();
    timerP.start();
    calculated = simpsonsIntegrationParallel(a = 0.0, b = 6000.0, N = 6000000, f = f3);
    timerP.stop();
    writeln((abs(calculated - exact) <= maxErr));
    timer.clear();
    timer.start();
    calculated = simpsonsIntegration(a = 0.0, b = 6000.0, N = 6000000, f = f3);
    timer.stop();
    writeln((abs(calculated - exact) <= maxErr));
    writeln((timerP.elapsed() < timerMargin*timer.elapsed()));
